### ISSUE TITLE
Snowflake Dialect

### ISSUE THREAD

**Issue by lcclark** [hunyadi/pysqlsync#4]
Hello! We are hoping to use this package to sync data from Canvas to our data warehouse that is in Snowflake. Does the team currently have plans to add Snowflake as a provided dialect, or should we start on adding the dialect ourselves given the provided instructions? Thanks!

**Comment by hunyadi** [comment]
Unfortunately, we don't have any short-term or mid-term plans to integrate a Snowflake connector, and thus add Snowflake as a supported dialect to *pysqlsync*. However, if you are open to contributing, I am more than happy to help with hints or code review.

**Comment by lcclark** [comment]
Got it, thanks so much for the response ! We have decided to move forward with the Data2 API instead of the Sync for now, with plans to revisit the sync option in the future, so will be in touch in the coming months. Thanks again!
