### ISSUE TITLE
List[] generates a 1..n relation instead of 0..n

### ISSUE THREAD

**Issue by EnikoCsordas** [hunyadi/pysqlsync#6]

**Comment by hunyadi** [comment]
The recommended practice is to declare nullable one-to-many relations as `Optional[List[T]]`, and non-nullable one-to-many relations as `List[T]`. Both are supported in `pysqlsync`, and expand into a relation table with a unique identifier, a reference to the primary key in the origin table, and a reference to the primary key in the target ("many") table, e.g.

```sql
CREATE TABLE "AssessmentItem_max_score_Score" (
"uuid" uuid NOT NULL,
"AssessmentItem_max_score" uuid NOT NULL,
"Score_uuid" uuid NOT NULL,
CONSTRAINT "pk_AssessmentItem_max_score_Score" PRIMARY KEY ("uuid")
);
ALTER TABLE "AssessmentItem_max_score_Score"
ADD CONSTRAINT "jk_AssessmentItem_max_score" FOREIGN KEY ("AssessmentItem_max_score") REFERENCES "AssessmentItem" ("uuid"),
ADD CONSTRAINT "jk_AssessmentItem_max_score_Score" FOREIGN KEY ("Score_uuid") REFERENCES "Score" ("uuid");
```
